-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT it.ITEM_ID
    FROM ITEM_INFO ii
    LEFT JOIN ITEM_TREE it
        ON ii.ITEM_ID = it.PARENT_ITEM_ID
    WHERE RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC;