-- 코드를 입력하세요
SELECT ugb.TITLE as TITLE, ugr.BOARD_ID as BOARD_ID, ugr.REPLY_ID as REPLY_ID, ugr.WRITER_ID as WRITER_ID, ugr.CONTENTS as CONTENTS, ugr.CREATED_DATE as CREATED_DATE
FROM USED_GOODS_REPLY ugr
JOIN USED_GOODS_BOARD ugb ON ugr.BOARD_ID = ugb.BOARD_ID
WHERE YEAR(ugb.CREATED_DATE) = 2022 AND MONTH(ugb.CREATED_DATE) = 10
ORDER BY ugr.CREATED_DATE, ugb.TITLE;